const englishText = {
  brand: {
    appName: 'FocusKube',
    emptyStateNameFocus: 'Focus',
    emptyStateNameKube: 'Kube',
    emptyStateTagline: 'Deep Visibility into your Kubernetes Clusters.',
  },
  theme: {
    dark: 'Dark',
    light: 'Light',
    contrast: 'Contrast'
  },
  auth: {
    signInTitle: 'Sign in',
    copy: 'Enter your email to continue.',
    emailLabel: 'Email',
    emailPlaceholder: 'you@example.com',
    continueButton: 'Continue',
    emailRequired: 'Email is required.',
  },
  confirmDialog: {
    defaultTitle: 'Confirm action',
    deleteTitle: 'Confirm delete',
    closeLabel: 'Close dialog',
    confirm: 'Confirm',
    no: 'No',
    deleteQuestion: (target: string) => `Are you sure you want to delete ${target}?`,
    uninstallTitle: 'Confirm uninstall',
    uninstallQuestion: (release: string) => `Are you sure you want to uninstall release "${release}"?`,
    uninstall: 'Uninstall',
    rollbackTitle: 'Confirm rollback',
    rollbackQuestion: (name: string, revision: number | string) => `Are you sure you want to roll back ${name} to revision ${revision}?`,
    rollback: 'Roll back',
    saveTitle: 'Confirm save',
    removeTitle: 'Confirm remove',
    remove: 'Remove',
    yesContinue: 'Continue',
  },
  common: {
    close: '✕',
    cancel: 'Cancel',
    save: 'Save',
    loading: 'Loading…',
    allNamespaces: 'All namespaces',
    selectedNamespacesSuffix: 'selected',
    selectContextToListApplications: 'Select a context to list applications.',
    noApplicationsFound: 'No applications found.',
    loadingApplications: 'Loading…',
    searchApplications: 'Search Applications...',
    refresh: 'Refresh',
    selectNamespacesTitle: 'Select namespaces',
    validate: 'Validate',
    validating: 'Validating…',
    yamlValid: 'YAML is valid.',
    yamlValidationFailed: 'YAML validation failed.',
    add: 'Add',
    install: 'Install',
    upgrade: 'Upgrade',
    delete: 'Delete',
    backToConfig: 'Back to Config',
    allApplications: 'All applications',
    selectApplications: 'Select applications',
    selectedCountSuffix: 'selected',
    selectAll: 'Select all',
    actions: 'Actions',
    resourceType: 'Resource type',
    namespace: 'Namespace',
    chart: 'Chart',
    chartVersion: 'Chart Version',
    latest: 'Latest',
    currentManifest: 'Current Manifest',
    newManifest: 'New Manifest',
    support: 'Support',
    resizeSidebar: 'Resize sidebar',
    emptyWorkspace: 'empty workspace',
    loadingPage: 'Loading...',
    selectRow: 'Select row',
  },
  modal: {
    preferences: 'Preferences',
    loadingSettings: 'Loading settings...',
  },
  toast: {
    refreshingApplications: 'refreshing applications',
  },
  activityBar: {
    label: 'Activity bar',
    explorer: 'Explorer',
    search: 'Search',
    noClustersFound: 'No clusters found.',
  },
  minikube: {
    title: 'Minikube Local Cluster',
    installed: 'Installed',
    notInstalled: 'Not Installed',
    clusterStatus: 'Cluster Status',
    checkingStatus: 'Checking cluster status...',
    name: 'Name:',
    namePlaceholder: 'minikube',
    status: 'Status:',
    clusterStopped: 'Cluster Stopped',
    notInstalledSetup: 'Not Installed: Setup Minikube. Steps Below',
    kubernetes: 'Kubernetes:',
    ipAddress: 'IP Address:',
    driver: 'Driver:',
    clusterControl: 'Cluster Control',
    starting: 'Starting...',
    stopping: 'Stopping...',
    deleting: 'Deleting...',
    start: 'Start',
    stop: 'Stop',
    delete: 'Delete',
    clusterParameters: 'Cluster Parameters',
    cpus: 'CPUs:',
    memory: 'Memory:',
    memoryPlaceholder: '4096m',
    dockerDesktop: 'Docker Desktop',
    hyperV: 'Hyper-V',
    virtualBox: 'VirtualBox',
    openingExplorer: 'Opening Explorer...',
    openResourceExplorer: 'Open Resource Explorer',
    setupSteps: 'Cluster Setup Steps',
    setupInstructions:
      '1. Download the script for your platform and driver.\n2. Run it from a terminal or shell on your machine.\n3. Windows Hyper-V scripts require administrator permission to enable the feature. Docker Desktop and VirtualBox scripts may still prompt for elevation when their installers run.\n4. macOS and Linux scripts may ask for sudo when installing packages.\n5. After the script finishes, come back here to start or manage Minikube.',
  },
  helm: {
    releasesTitle: 'Helm Releases',
    chartsTitle: 'Helm Charts',
    repoCatalog: 'Repo catalog',
    showAllInstallableCharts: 'Show all installable charts from your Helm repositories',
    installRelease: 'Install a new Helm release',
    installReleaseButton: 'Install Release',
    addRepository: 'Add Repository',
    addHelmRepositoryTitle: 'Add Helm Repository',
    repositoryName: 'Repository Name',
    repositoryUrl: 'Repository URL',
    commonRepositories: 'Common repositories:',
    releaseName: 'Release Name',
    releaseVersion: 'Target Chart Version (optional)',
    valuesYaml: 'Values (YAML)',
    preview: 'Preview',
    configuration: 'Configuration',
    diff: 'Diff',
    history: 'History',
    values: 'Values',
    uninstall: 'Uninstall',
    upgradeRelease: 'Upgrade Release',
    noReleasesFound: 'No Helm releases found.',
    releasesCount: (count: number) => `${count} releases`,
    chartsCount: (count: number) => `${count} charts`,
    refreshingResources: 'refreshing helm resources',
    loadingCharts: 'Loading charts...',
    loadingChartDefaults: 'Loading chart defaults...',
    loadingCurrentValues: 'Loading current values...',
    loadingManifest: 'Loading manifest...',
    loadChartsError: 'Failed to load charts',
    uploadError: 'Please upload a .tgz or .tar.gz chart file',
    generating: 'Generating...',
    installing: 'Installing...',
    previewTitle: 'Preview what will be deployed',
    installReleaseTitle: 'Install release',
    noChartsFound: 'No charts found. Add a Helm repository to get started.',
    noChartsDeployed: 'No charts deployed in the selected namespace. Tick ΓÇ£Repo catalogΓÇ¥ to browse installable charts.',
    installFailed: 'Installation failed',
    upgradeFailed: 'Upgrade failed',
    selectContextToListReleases: 'Select a context to list Helm releases.',
    selectCompleteForm: 'Complete the form',
    addRepoHint: 'A unique name to identify this repository',
    repoUrlHint: 'The Helm repository URL',
    addRepositoryError: 'Failed to add repository',
    currentVersionPrefix: 'Current:',
    madeChangesOrSelectVersion: 'Make changes or select a new version',
    makeChangesFirst: 'Make changes first',
    releaseDetailsTitle: (name: string) => `Release — ${name}`,
    appVersion: 'App version',
    updated: 'Updated',
    uploadChart: 'Upload Chart (.tgz)',
    releaseNamePlaceholder: 'my-release',
    namespace: 'Namespace',
    targetChartVersionOptional: 'Target Chart Version (optional)',
    keepCurrentVersion: 'Leave empty to keep current version',
    revisionShort: 'Rev',
    loadingHistory: 'Loading…',
    selectChart: 'Select a chart...',
  },
  portForwarding: {
    title: 'Port Forwarding',
    description: 'Forward a pod or service port from the current cluster to your local machine.',
    target: 'Target',
    resource: 'Resource',
    podLabel: 'Pods',
    serviceLabel: 'Services',
    noResourcesFound: (kind: string) => `No ${kind} found`,
    selectTargetStart: 'Select a target and start forwarding.',
    selectContextBeforeStart: 'Select a context before starting port forwarding.',
    pickTargetPort: 'Pick a target and target port first.',
    startingPrefix: (kind: string) => `Starting ${kind.slice(0, -1)} port forward...`,
    stopped: 'Port forwarding stopped.',
    selectContext: 'Select a context to browse targets.',
    startPortForward: 'Start Port Forward',
    stopPortForward: 'Stop Port Forward',
    open: 'Open',
    targetPort: 'Target Port',
    localPort: 'Local Port',
    status: 'Status',
    portForwardProcessExitedPrefix: (code: number) => `Port-forward process exited with code ${code}.`,
    forwardingPrefix: (kind: string, name: string) => `Forwarding ${kind}/${name}...`,
    forwardingOnLoopback: (port: number) => `Forwarding on 127.0.0.1:${port}`,
    socketFailed: 'Port forwarding socket failed.',
    refreshingTargets: 'refreshing forwarding targets',
  },
  topbar: {
    openMenu: 'Open menu',
    userMenu: 'User menu',
    settings: 'Settings',
    preferences: 'Preferences',
    loadingSettings: 'Loading settings...',
    closeSettings: 'Close settings',
    theme: 'Theme',
    logLevel: 'Log level',
    effectivePrefix: 'Effective:',
    envPrefix: 'ENV:',
    uiOverrideActive: 'UI override active',
    desktopOnly: 'Log level is editable only in desktop mode.',
    failedToUpdateLogLevel: 'Failed to update log level.',
    saving: 'Saving...',
    rolePrefix: 'Role:',
    permissionsSuffix: 'permissions',
    language: 'Language',
  },
  resource: {
    selectContextToBegin: 'Select a context to begin. Use the Azure panel to pull AKS credentials.',
    searchPods: 'Search Pods...',
    filterByName: 'Filter by name...',
    refreshingResourcesAfterAuth: 'Refreshing resources after authentication',
    refreshing: 'Refreshing...',
    liveSync: 'Live sync',
    connecting: 'Connecting',
    showEventsFromRange: 'Show events from this time range',
    allTime: 'All time',
    last5Minutes: 'Last 5 minutes',
    last15Minutes: 'Last 15 minutes',
    last1Hour: 'Last 1 hour',
    last6Hours: 'Last 6 hours',
    last24Hours: 'Last 24 hours',
    exportFilteredResources: 'Export the filtered resources',
    retry: 'Retry',
    addNewResource: 'Add a new resource (deploy YAML)',
    addNewResourceLabel: 'Add a new resource',
    loading: 'Loading…',
    noResourcesFound: 'No resources found.',
    selectAll: 'Select all',
    clickToSort: 'Click to sort',
    nothingToExport: 'Nothing to export — the filtered list is empty.',
    colName: 'Name',
    colNamespace: 'Namespace',
    colCpu: 'CPU',
    colMemory: 'Memory',
    colContainers: 'Containers',
    colRestarts: 'Restarts',
    colControlled: 'Controlled',
    colNode: 'Node',
    colQos: 'QoS',
    colStatus: 'Status',
    colAge: 'Age',
    colPods: 'Pods',
    colReplicas: 'Replicas',
    colDesired: 'Desired',
    colCurrent: 'Current',
    colReady: 'Ready',
    colUpToDate: 'Up-to-date',
    colAvailable: 'Available',
    colNodeSelector: 'Node Selector',
    colCompletions: 'Completions',
    colConditions: 'Conditions',
    colSchedule: 'Schedule',
    colSuspend: 'Suspend',
    colActive: 'Active',
    colLastSchedule: 'Last schedule',
    colNextExecution: 'Next execution',
    colTimeZone: 'Time zone',
    colLabels: 'Labels',
    colKeys: 'Keys',
    colType: 'Type',
    colMessage: 'Message',
    colInvolvedObject: 'Involved Object',
    colReason: 'Reason',
    colSource: 'Source',
    colCount: 'Count',
    colLastSeen: 'Last Seen',
    showDetails: 'Show details',
    openDetailsTitle: 'Open details',
    viewLogs: 'View logs',
    openPodLogsTitle: 'Open pod logs',
    openShell: 'Open shell',
    openExecShellTitle: 'Open exec shell',
    restartDeploymentAction: 'Restart deployment',
    triggerRolloutRestart: 'Trigger rollout restart',
    openDeploymentOverview: 'Open deployment overview',
    openDeploymentActions: 'Open deployment actions',
    openResourceKindOverview: (kind: string) => `Open ${kind} overview`,
    editYamlTitle: 'Edit resource YAML',
    selectRow: 'Select row',
    resizeColumnTitle: (label: string) => `Resize ${label} column`,
    realtimeWatchTitle: (state: string) => `Realtime watch is ${state}`,
    itemsCountSuffix: 'items',
    lastUpdatePrefix: 'Last update:',
    accessDeniedStopped: ' — access denied, so automatic retries were stopped. Pick a different namespace or click Refresh.',
    stoppedAfterAttempts: (n: number) => ` — stopped after ${n} attempts. Click Retry to try again.`,
    roleCannotListPrefix: 'Your current role cannot list ',
    roleCannotListSuffix:
      ' across all namespaces. Pick a namespace from the dropdown, or type one in the top bar and click Apply.',
    exportAsLabel: (format: string) => `Export as ${format}`,
    exportedSummary: (count: number, plural: string, format: string) => `Exported ${count} ${plural} as ${format}`,
    resourceDeleted: 'Resource deleted.',
    restartingDeployment: (name: string) => `Restarting deployment ${name}...`,
    restartRequested: (name: string) => `Restart requested for ${name}. Watching rollout...`,
    rolloutFailed: (name: string) => `Deployment ${name} rollout failed.`,
    rolloutCompleted: (name: string) => `Deployment ${name} rollout completed.`,
    noLabels: 'No labels',
    loadingMore: 'Loading more…',
    scrollToLoadMore: 'Scroll to load more',
    containerReadyAriaLabel: (name: string, ready: boolean) => `${name}: ${ready ? 'ready' : 'not ready'}`,
    notReady: 'Not Ready',
    statePrefix: 'State:',
    restartsPrefix: 'Restarts:',
    notStarted: 'Not Started',
    runningState: 'Running',
    unknownState: 'Unknown',
    cpuColumnTooltip: 'CPU in millicores. 1000m = 1 vCPU/core.',
    memoryColumnTooltip: 'Memory in mebibytes/gibibytes. 1 Mi = 1024 KiB.',
    liveCpuUsageTooltip: (value: number) =>
      `Live CPU usage from metrics server is ${value}m. The m = millicores (1000m = 1 core).`,
    fallbackCpuRequestTooltip: (value: number) =>
      `Fallback value from pod resource requests is ${value}m. The m = millicores (1000m = 1 core).`,
    noCpuMetricsConfigured: 'No live metrics and no CPU request configured.',
    liveMemoryUsageTooltip: 'Live memory usage from metrics server. Mi = mebibytes (1024 KiB).',
    fallbackMemoryRequestTooltip: 'Fallback value from pod resource requests. Mi = mebibytes (1024 KiB).',
    noMemoryMetricsConfigured: 'No live metrics and no memory request configured.',
  },
  applications: {
    title: 'Applications',
    overview: 'Overview',
    clusterOverview: 'Cluster Overview',
    clusterOverviewDescription: 'Workloads and Helm releases across the entire cluster',
    selectContextForOverview: 'Select a Kubernetes context to view the cluster overview.',
    loadingOverview: 'Loading overview',
    deployments: 'Deployments',
    replicaSets: 'Replica Sets',
    cronJobs: 'Cron Jobs',
    daemonSets: 'Daemon Sets',
    statefulSets: 'Stateful Sets',
    jobs: 'Jobs',
    helmReleases: 'Helm Releases',
    selectedCountSuffix: 'selected',
    refresh: 'Refresh',
    copyInstance: 'Copy Instance',
    instance: 'Instance',
    application: 'Application',
    namespace: 'Namespace',
    managedBy: 'Managed By',
    version: 'Version',
    age: 'Age',
    status: 'Status',
    metrics: 'Metrics',
    metricsDescription: 'Displaying metrics from Kubernetes Metrics Server',
    cpuUsage: 'CPU Usage',
    memoryUsage: 'Memory Usage',
    podStatus: 'Pod Status',
    nodeStatus: 'Node Status',
    ready: 'Ready',
    accessRestricted: 'Access restricted',
    nodesForbidden: 'You do not have permission to view node status.',
    recentEvents: 'Recent Events',
    latestEvents: 'Latest cluster events',
    showAllEvents: 'Show all events',
    properties: 'Properties',
    pods: 'Pods',
    workloadResources: 'Workload Resources',
    loadingPods: 'Loading pods…',
    noPodsFound: 'No pods found',
    name: 'Name',
    node: 'Node',
    cpu: 'CPU',
    memory: 'Memory',
    component: 'Component',
    unknown: 'Unknown',
    event: 'Event',
  },
  observability: {
    selectContext: 'Please select a Kubernetes context from the sidebar to view event correlations.',
    timeRange: 'Time Range:',
    workloadChanges: 'Workload Changes:',
    warningEvents: 'Warning Events:',
    correlated: 'Correlated:',
    noEventsInRange: 'No events recorded in this time range.',
    time: 'Time:',
    namespace: 'Namespace:',
    category: 'Category:',
    changeType: 'Change Type:',
    severity: 'Severity:',
    summary: 'Summary:',
    correlation: 'Correlation:',
    reason: 'Reason:',
    involvedObject: 'Involved Object:',
    before: 'Before:',
    after: 'After:',
  },
  observabilityPanel: {
    selectContext: 'Please select a Kubernetes context from the sidebar to use observability features.',
    loading: 'Loading...',
    unavailableTitle: 'Observability Unavailable',
    unavailableDescription: 'Something went wrong loading the observability store. Try reloading, or check the backend logs for details.',
    title: 'Observability & Time-Travel Debugging',
    subtitle: 'Record and replay cluster state changes over time.',
    recording: 'Recording',
    stopRecording: 'Stop Recording',
    starting: 'Starting...',
    retry: 'Retry',
    startRecording: 'Start Recording',
    timelineTab: '◷ Timeline',
    logsTab: '📋 Multi-Pod Logs',
    correlationTab: '🔗 Event Correlation',
    recordingNotActivePrefix: 'Recording not active:',
    startRecordingHint: 'Click "Start Recording" above to begin capturing cluster state changes. Without an active recording, the',
    timelineScrubber: 'timeline scrubber',
    correlationDashboard: 'correlation dashboard',
    willShowNoData: 'will show no data.',
  },
  timeline: {
    selectContext: 'Please select a Kubernetes context from the sidebar to view the timeline.',
    clusterStatePrefix: 'Cluster State at',
    noWorkloadState: 'No workload state recorded at this time.',
    kind: 'Kind',
    namespace: 'Namespace',
    name: 'Name',
    changeType: 'Change Type',
    summary: 'Summary',
    uid: 'UID',
    severity: 'Severity',
    reason: 'Reason',
    before: 'Before:',
    after: 'After:',
    clusterScoped: '(cluster-scoped)',
    clusterTimeline: 'Cluster Timeline',
  },
  multiPodLogs: {
    pods: 'Pods:',
    podNamesPlaceholder: 'Enter pod names (e.g., my-pod-1, my-pod-2) separated by commas',
    filterPlaceholder: 'Filter logs...',
    enterPodsHint: 'Enter pod names above to start viewing merged logs from multiple replicas.',
    waitingForLogs: 'Waiting for logs...',
  },
  topology: {
    selectContext: 'Select a context to view its topology.',
    title: 'Topology',
    loading: 'Loading…',
    selectNamespace: 'Select a namespace…',
    selectNamespaceToView: 'Select a namespace to view its object graph.',
    selectApplicationsToView: 'Select one or more applications to view their topology.',
    noObjectsFound: 'No objects found for the selected application(s).',
    couldNotLoadPrefix: "Couldn't load:",
    inThisNamespace: 'in this namespace — the graph below reflects everything else.',
    loadingTopology: 'loading topology',
  },
  resourceDetail: {
    logs: 'Logs',
    shell: 'Shell',
    restartDeployment: 'Restart Deployment',
    deploymentActions: 'Deployment Actions',
    editYaml: 'Edit YAML',
    deletePrefix: 'Delete',
    name: 'Name',
    kind: 'Kind',
    warningPrefix: 'WARNING: You are deleting pod',
    destructiveActionNotice: 'This is an immediate destructive action and may interrupt traffic.',
    continuePrompt: 'Do you want to continue?',
    yaml: 'YAML',
    overview: 'Overview',
    details: 'Details',
    pod: 'Pod',
    deployment: 'Deployment',
    clusterScoped: '(cluster-scoped)',
    readOnlyNotice: 'Read-only — your role cannot edit this resource.',
    decoding: 'Decoding…',
    yamlValidUpdate: (kind: string, name: string, namespace?: string) =>
      `YAML is valid. Saving will update ${kind} ${name}${namespace ? ` in ${namespace}` : ''}.`,
    yamlValidateHint: 'Validate the YAML against the cluster before saving — this checks it server-side without applying it.',
    decodedValues: 'Decoded values (server-side, requires ALLOW_SECRET_REVEAL=true)',
    properties: 'Properties',
    metrics: 'Metrics',
    metricsDescription: 'Displaying metrics from Kubernetes Metrics Server',
    resourceUsage: 'Resource Usage',
    cpuUsage: 'CPU Usage',
    memoryUsage: 'Memory Usage',
    deploymentMetricsDescription: 'Live deployment totals sampled every 15 seconds while this overview is open.',
    metricSelection: 'Metric selection',
    reporting: 'Reporting',
    now: 'Now',
    totalMemory: 'Total Memory',
    podsReporting: 'Pods Reporting',
    loadingMetrics: 'Loading metrics…',
    metricsUnavailable: 'Metrics unavailable',
    noDeploymentPods: 'No deployment pods found',
    noVolumesDefined: 'No volumes defined',
    containers: 'Containers',
    vulnerabilities: 'Vulnerabilities',
    events: 'Events',
    loadingEvents: 'Loading events…',
    noEventsFound: 'No events found',
    images: 'Images',
    labels: 'Labels',
    annotations: 'Annotations',
    status: 'Status',
    image: 'Image',
    ports: 'Ports',
    environment: 'Environment',
    mounts: 'Mounts',
    requests: 'Requests',
    limits: 'Limits',
    created: 'Created',
    actionsTab: 'Actions',
    execTab: 'Exec',
    secretTab: 'Secret',
    dash: '-',
    wildcard: '*',
    controlled: 'Controlled',
    node: 'Node',
    podIP: 'Pod IP',
    podIPs: 'Pod IPs',
    serviceAccount: 'Service Account',
    qosClass: 'QoS Class',
    conditions: 'Conditions',
    tolerations: 'Tolerations',
    podAntiAffinities: 'Pod Anti Affinities',
    ruleCount: (n: number) => `${n} Rule${n > 1 ? 's' : ''}`,
    podVolumesTitle: 'Pod Volumes',
    volumeProjected: 'Projected',
    volumeConfigMap: 'ConfigMap',
    volumeSecretType: 'Secret',
    volumeEmptyDir: 'EmptyDir',
    volumeDefault: 'Volume',
    runningReady: 'running, ready',
    tcp: 'TCP',
    environmentalVariablesCount: (n: number) => `${n} Environmental Variables`,
    mountsCount: (n: number) => `${n} Mounts`,
    mountFrom: (path: string, name: string) => `${path} from ${name}`,
    readOnlySuffix: ' (ro)',
    vulnerabilitiesPlaceholder:
      'To perform automatic scanning, FocusKube Security Center requires enabling the Trivy Operator. This view is a placeholder until a vulnerability provider is integrated.',
    normalEventType: 'Normal',
    eventReasonFallback: 'Event',
    labelsCount: (n: number) => `${n} Labels`,
    annotationsCount: (n: number) => `${n} Annotations`,
    cpuPrefix: 'CPU:',
    memoryPrefix: 'Memory:',
    updatedPrefix: 'Updated:',
    errorPrefix: 'Error:',
    cpuRequestsLegend: 'CPU Requests',
    cpuLimitsLegend: 'CPU Limits',
    replicas: 'Replicas',
    updatedReplicas: 'Updated Replicas',
    availableReplicas: 'Available Replicas',
    unavailableReplicas: 'Unavailable Replicas',
    strategy: 'Strategy',
    rolloutStatus: 'Rollout Status',
    configuration: 'Configuration',
    uid: 'UID',
    revision: 'Revision',
    generation: 'Generation',
    observedGeneration: 'Observed Generation',
    maxSurge: 'Max Surge',
    minReadySeconds: 'Minimum Ready Seconds',
    progressDeadlineSeconds: 'Progress Deadline Seconds',
    revisionHistoryLimit: 'Revision History Limit',
    paused: 'Paused',
    imagePullPolicy: 'Image Pull Policy',
    command: 'Command / Arguments',
    readinessProbe: 'Readiness Probe',
    livenessProbe: 'Liveness Probe',
    noConditions: 'No conditions reported',
    desired: 'Desired',
    current: 'Current',
    ready: 'Ready',
    upToDate: 'Up-to-date',
    available: 'Available',
    nodeSelector: 'Node Selector',
    updateStrategy: 'Update Strategy',
    serviceName: 'Service Name',
    completions: 'Completions',
    parallelism: 'Parallelism',
    active: 'Active',
    schedule: 'Schedule',
    suspend: 'Suspend',
    lastSchedule: 'Last Schedule',
    timeZone: 'Time Zone',
    type: 'Type',
    clusterIP: 'ClusterIP',
    clusterIpLabel: 'Cluster IP',
    clusterIpsLabel: 'Cluster IPs',
    externalIPs: 'External IPs',
    loadBalancerIngress: 'Load Balancer Ingress',
    sessionAffinity: 'Session Affinity',
    externalTrafficPolicy: 'External Traffic Policy',
    selector: 'Selector',
    noPortsDefined: 'No ports defined',
    colPort: 'Port',
    colTargetPort: 'Target Port',
    colProtocol: 'Protocol',
    colNodePort: 'Node Port',
    addressType: 'Address Type',
    endpointsTitle: 'Endpoints',
    noEndpoints: 'No endpoints',
    addresses: 'Addresses',
    hostname: 'Hostname',
    colNodeName: 'Node Name',
    noAddresses: 'No addresses',
    notReadyAddressesTitle: 'Not Ready Addresses',
    noNotReadyAddresses: 'No not-ready addresses',
    colIP: 'IP',
    ingressClass: 'Ingress Class',
    defaultBackend: 'Default Backend',
    tlsHosts: 'TLS Hosts',
    rulesTitle: 'Rules',
    noRulesDefined: 'No rules defined',
    colHost: 'Host',
    colPath: 'Path',
    colPathType: 'Path Type',
    colBackendService: 'Backend Service',
    colBackendPort: 'Backend Port',
    controller: 'Controller',
    isDefaultClass: 'Is Default Class',
    parameters: 'Parameters',
    podSelector: 'Pod Selector',
    policyTypes: 'Policy Types',
    ingressRulesTitle: 'Ingress Rules',
    egressRulesTitle: 'Egress Rules',
    colRule: 'Rule',
    colFrom: 'From',
    colTo: 'To',
    noIngressRules: 'No ingress rules (deny all)',
    noEgressRules: 'No egress rules (deny all)',
    ruleLabel: (n: number) => `Rule ${n}`,
    podsPeerSummary: (v: string) => `pods: ${v}`,
    namespacePeerSummary: (v: string) => `ns: ${v}`,
    ipPeerSummary: (v: string) => `ip: ${v}`,
    allCap: 'All',
    allLower: 'all',
    hardLimitsUsedTitle: 'Hard Limits / Used',
    noQuotaEntries: 'No quota entries',
    hard: 'Hard',
    used: 'Used',
    noLimitsDefined: 'No limits defined',
    default: 'Default',
    defaultRequest: 'Default Request',
    max: 'Max',
    min: 'Min',
    limitHeading: (n: number) => `Limit ${n}`,
    scaleTarget: 'Scale Target',
    minReplicas: 'Min Replicas',
    maxReplicas: 'Max Replicas',
    currentReplicas: 'Current Replicas',
    desiredReplicas: 'Desired Replicas',
    noMetricsConfigured: 'No metrics configured',
    metricHeading: (n: number) => `Metric ${n}`,
    minAvailable: 'Min Available',
    maxUnavailable: 'Max Unavailable',
    currentHealthy: 'Current Healthy',
    desiredHealthy: 'Desired Healthy',
    disruptionsAllowed: 'Disruptions Allowed',
    expectedPods: 'Expected Pods',
    holderIdentity: 'Holder Identity',
    leaseDurationSeconds: 'Lease Duration Seconds',
    acquireTime: 'Acquire Time',
    renewTime: 'Renew Time',
    leaseTransitions: 'Lease Transitions',
    automountToken: 'Automount Token',
    secretsLabel: 'Secrets',
    imagePullSecrets: 'Image Pull Secrets',
    apiGroups: 'API Groups',
    resourcesLabel: 'Resources',
    resourceNames: 'Resource Names',
    verbs: 'Verbs',
    roleRef: 'Role Ref',
    subjectsTitle: 'Subjects',
    noSubjects: 'No subjects',
    subjectHeading: (n: number) => `Subject ${n}`,
    apiGroup: 'API Group',
    group: 'Group',
    scope: 'Scope',
    pluralLabel: 'Plural',
    singular: 'Singular',
    shortNames: 'Short Names',
    versionsTitle: 'Versions',
    noVersions: 'No versions',
    served: 'Served',
    storage: 'Storage',
    deprecated: 'Deprecated',
    accessModes: 'Access Modes',
    storageClass: 'Storage Class',
    volumeName: 'Volume Name',
    volumeMode: 'Volume Mode',
    requestedStorage: 'Requested Storage',
    capacity: 'Capacity',
    provisioner: 'Provisioner',
    reclaimPolicy: 'Reclaim Policy',
    volumeBindingMode: 'Volume Binding Mode',
    allowVolumeExpansion: 'Allow Volume Expansion',
    mountOptions: 'Mount Options',
    falseLower: 'false',
    finalizers: 'Finalizers',
    reason: 'Reason',
    message: 'Message',
    count: 'Count',
    firstSeen: 'First Seen',
    lastSeen: 'Last Seen',
    involvedObjectLabel: 'Involved Object',
    source: 'Source',
    trueLabel: 'True',
    falseLabel: 'False',
    unschedulable: 'Unschedulable',
    internalIP: 'Internal IP',
    externalIP: 'External IP',
    podCIDR: 'Pod CIDR',
    kubeletVersion: 'Kubelet Version',
    osImage: 'OS Image',
    containerRuntime: 'Container Runtime',
    kernelVersion: 'Kernel Version',
    architecture: 'Architecture',
    allocatable: 'Allocatable',
    noConditionsReported: 'No conditions reported',
    taintsTitle: 'Taints',
    noTaints: 'No taints',
    value: 'Value',
    effect: 'Effect',
    data: 'Data',
    loadingData: 'Loading…',
    addButton: '+ Add',
    noDataEntries: 'No data entries',
    hideSecretValue: 'Hide secret value',
    showSecretValue: 'Show secret value',
    deleteKey: 'Delete key',
    deleteKeyConfirm: (key: string, kindLabel: string) => `Delete key "${key}" from this ${kindLabel}?`,
    secretKindLabel: 'secret',
    configMapKindLabel: 'config map',
    localChangeUntilSave: 'This change is local until you click Save.',
    removedKeysWarning: (count: number, preview: string, more: string) => `You removed ${count} key(s): ${preview}${more}.`,
    andMoreSuffix: (n: number) => ` and ${n} more`,
    savingWillRemove: 'Saving will permanently remove them from Kubernetes.',
    savedSuccessfully: 'Saved successfully.',
    revert: 'Revert',
    keyColumn: 'Key',
    agoSuffix: 'ago',
  },
  sidebar: {
    k8sCluster: 'K8S Cluster',
    starredContexts: 'STARRED CONTEXTS',
    noStarredContexts: 'No starred contexts yet.',
    azureConnections: 'Azure connections',
    awsConnections: 'AWS connections',
    azureAccounts: ' Azure / AKS',
    awsAccounts: 'AWS / EKS',
    connect: 'Connect',
    disconnect: 'Disconnect',
    star: 'Star',
    unstar: 'Unstar',
    removeContext: 'Remove context',
    working: 'working',
    connecting: 'Connecting',
    loadingAzureAccounts: 'Loading Azure accounts...',
    checkAzureAccount: 'Click Azure / AKS to check cloud account.',
    noResourceGroups: 'No resource groups found.',
    noClustersFound: 'No clusters found.',
    noContextImported: 'No context imported yet.',
    loadingAwsClusters: 'Loading AWS clusters...',
    loadingResourceGroups: 'loading resource groups',
    loadingClusters: 'loading clusters',
    loadingContext: 'loading context',
    checkAwsAccount: 'Click AWS / EKS to check cloud account.',
    noEksClustersFound: 'No EKS clusters found.',
    actionsFor: (name: string) => `Actions for ${name}`,
    localKubeconfigs: 'Local Kubeconfigs',
    noLocalKubeconfigs: 'No local kubeconfigs uploaded yet.',
    checkingLocalAzureAuth: 'checking local Azure authentication',
    authenticateLocalAzure: 'Authenticate Azure (local scope) to view contexts.',
    noContextsInFile: 'No contexts found in this file.',
    disconnectedClickToConnect: 'Disconnected — click to connect',
    localMinikube: 'Local Minikube',
  },
  columns: {
    chooseVisible: 'Choose visible columns',
    visibleColumns: 'Visible columns',
    resetColumns: 'Reset Columns',
  },
  aws: {
    connectionsTitle: 'AWS / EKS Connections',
    accountTitle: 'AWS / EKS Account',
    checking: 'Checking...',
    configureConnection: 'Configure AWS connection',
    configureDescription: 'Choose SSO, access keys, or an IAM role profile for this session.',
    saveConnection: 'Save AWS connection',
    saving: 'Saving...',
    signIn: 'Sign in to AWS (device code)',
    signInProgress: 'AWS sign-in in progress...',
    signInProgressLabel: 'AWS sign-in in progress',
    waitingForDeviceCode: 'Waiting for AWS device code...',
    waitingForSignIn: 'Waiting for sign-in...',
    signOut: 'Sign out',
    signedOut: 'Signed out from AWS CLI SSO session.',
    signedIn: 'Signed in to AWS.',
    importCredsPrefix: 'Imported credentials for',
    loadingClusters: 'Loading clusters...',
    noClusters: 'No EKS clusters.',
    refresh: 'Refresh',
    sso: 'SSO',
    accessKeySecret: 'Access key + secret',
    iamRole: 'IAM role',
    profileName: 'Profile name',
    ssoSessionName: 'SSO session name',
    ssoStartUrl: 'SSO start URL',
    ssoRegion: 'SSO region',
    accountId: 'Account ID',
    roleName: 'Role name',
    accessKeyId: 'Access key ID',
    secretAccessKey: 'Secret access key',
    sessionTokenOptional: 'Session token (optional)',
    roleArn: 'Role ARN',
    sourceProfileOptional: 'Source profile name (optional)',
    roleSessionName: 'Role session name',
    defaultRegion: 'Default AWS region',
    open: 'Open',
    enterCode: 'and enter code',
    profileSaved: 'AWS auth profile saved. Refresh the account listing to verify access.',
    eksClusters: 'EKS Clusters',
    name: 'Name',
    region: 'Region',
    version: 'Version',
    status: 'Status',
  },
  azure: {
    connectionsTitle: 'Azure / AKS Connections',
    accountTitle: 'Account',
    checking: 'Checking…',
    signIn: 'Sign in to Azure',
    signInProgress: 'Azure sign-in in progress…',
    waitingForDeviceCode: 'Waiting for Azure device code…',
    waitingForSignIn: 'Waiting for sign-in…',
    cancelSignIn: 'Cancel',
    cancellingSignIn: 'Cancelling…',
    signOut: 'Sign out',
    signedOut: 'Signed out from Azure CLI session.',
    signedIn: 'Signed in to Azure.',
    importCredsPrefix: 'Imported credentials for',
    loadingClusters: 'Loading clusters…',
    noClusters: 'No AKS clusters.',
    refresh: 'Refresh',
    refreshing: 'Refreshing...',
    signingOut: 'Signing out...',
    loadingAccounts: 'Loading Azure accounts...',
    resyncTitle: 'Re-sync from Azure and reload this account into the sidebar',
    subscriptions: (count: number) => `${count} subscription${count === 1 ? '' : 's'}`,
  },
  deployment: {
    readOnlyNotice: 'Your role is read-only — deployment actions are disabled.',
    restart: 'Restart',
    rolloutRestart: 'Rollout restart',
    scale: 'Scale',
    apply: 'Apply',
    currentDesiredPrefix: 'current desired:',
    rolloutHistory: 'Rollout history',
    loadingHistory: 'Loading history…',
    revision: 'Revision',
    images: 'Images',
    created: 'Created',
    current: 'current',
    rollback: 'Rollback',
  },
  logs: {
    container: 'Container',
    follow: 'Follow',
    openInTerminal: 'Open in terminal tab',
    streaming: 'streaming',
    disconnected: 'disconnected',
  },
  exec: {
    container: 'Container',
    shell: 'Shell',
    terminal: 'Terminal',
    openInTerminal: 'Open in terminal',
    connected: 'connected',
    disconnected: 'disconnected',
  },
  terminalDock: {
    resizePanel: 'Resize terminal panel',
    dragToResize: 'Drag to resize terminal',
    openNewTerminal: 'Open new terminal',
    restoreTerminals: 'Restore terminals',
    minimizeTerminals: 'Minimize all terminals',
    shell: 'Shell',
    logs: 'Logs',
    ready: 'Ready',
    connected: 'connected',
    disconnected: 'disconnected',
    searchTerminal: 'Search terminal',
    searchTerminalContents: 'Search terminal contents',
    podLogs: 'Pod logs',
    searchPodLogs: 'Search pod logs',
    matches: (count: number) => `${count} matches`,
    allLines: 'all lines',
    previous: 'Prev',
    next: 'Next',
  }
} as const;

export const uiText = englishText;
