export const uiText = {
  brand: {
    appName: 'FocusKube',
    emptyStateNameFocus: 'Focus',
    emptyStateNameKube: 'Kube',
    emptyStateTagline: 'Deep Visibility into your Kubernetes Clusters.',
  },
  auth: {
    signInTitle: 'Sign in',
    copy: 'Enter your email to continue.',
    emailLabel: 'Email',
    emailPlaceholder: 'you@example.com',
    continueButton: 'Continue',
    emailRequired: 'Email is required.',
  },
  common: {
    close: '✕',
    cancel: 'Cancel',
    save: 'Save',
    loading: 'Loading…',
    allNamespaces: 'All namespaces',
    selectedNamespacesSuffix: 'selected',
    selectContextToListApplications: 'Select a context to list applications.',
    noApplicationsFound: 'No applications found.',
    loadingApplications: 'Loading…',
    searchApplications: 'Search Applications...',
    refresh: 'Refresh',
    selectNamespacesTitle: 'Select namespaces',
    validate: 'Validate',
    add: 'Add',
    install: 'Install',
    upgrade: 'Upgrade',
    delete: 'Delete',
    backToConfig: 'Back to Config',
    allApplications: 'All applications',
    selectApplications: 'Select applications',
    selectedCountSuffix: 'selected',
  },
  modal: {
    preferences: 'Preferences',
    loadingSettings: 'Loading settings...',
  },
  toast: {
    refreshingApplications: 'refreshing applications',
  },
  helm: {
    releasesTitle: 'Helm Releases',
    chartsTitle: 'Helm Charts',
    repoCatalog: 'Repo catalog',
    showAllInstallableCharts: 'Show all installable charts from your Helm repositories',
    installRelease: 'Install a new Helm release',
    installReleaseButton: 'Install Release',
    addRepository: 'Add Repository',
    addHelmRepositoryTitle: 'Add Helm Repository',
    repositoryName: 'Repository Name',
    repositoryUrl: 'Repository URL',
    commonRepositories: 'Common repositories:',
    releaseName: 'Release Name',
    releaseVersion: 'Target Chart Version (optional)',
    valuesYaml: 'Values (YAML)',
    preview: 'Preview',
    configuration: 'Configuration',
    diff: 'Diff',
    history: 'History',
    values: 'Values',
    uninstall: 'Uninstall',
    upgradeRelease: 'Upgrade Release',
    loadingCharts: 'Loading charts...',
    loadingChartDefaults: 'Loading chart defaults...',
    loadingCurrentValues: 'Loading current values...',
    loadingManifest: 'Loading manifest...',
    loadChartsError: 'Failed to load charts',
    uploadError: 'Please upload a .tgz or .tar.gz chart file',
    generating: 'Generating...',
    installing: 'Installing...',
    previewTitle: 'Preview what will be deployed',
    installReleaseTitle: 'Install release',
    noChartsFound: 'No charts found. Add a Helm repository to get started.',
    noChartsDeployed: 'No charts deployed in the selected namespace. Tick “Repo catalog” to browse installable charts.',
    installFailed: 'Installation failed',
    upgradeFailed: 'Upgrade failed',
    selectContextToListReleases: 'Select a context to list Helm releases.',
    selectCompleteForm: 'Complete the form',
    addRepoHint: 'A unique name to identify this repository',
    repoUrlHint: 'The Helm repository URL',
    addRepositoryError: 'Failed to add repository',
    currentVersionPrefix: 'Current:',
    madeChangesOrSelectVersion: 'Make changes or select a new version',
    makeChangesFirst: 'Make changes first',
  },
  portForwarding: {
    title: 'Port Forwarding',
    description: 'Forward a pod or service port from the current cluster to your local machine.',
    target: 'Target',
    resource: 'Resource',
    podLabel: 'Pods',
    serviceLabel: 'Services',
    noResourcesFound: (kind: string) => `No ${kind} found`,
    selectTargetStart: 'Select a target and start forwarding.',
    selectContextBeforeStart: 'Select a context before starting port forwarding.',
    pickTargetPort: 'Pick a target and target port first.',
    startingPrefix: (kind: string) => `Starting ${kind.slice(0, -1)} port forward...`,
    stopped: 'Port forwarding stopped.',
    selectContext: 'Select a context to browse targets.',
    startPortForward: 'Start Port Forward',
    stopPortForward: 'Stop Port Forward',
    open: 'Open',
    targetPort: 'Target Port',
    localPort: 'Local Port',
    status: 'Status',
    portForwardProcessExitedPrefix: (code: number) => `Port-forward process exited with code ${code}.`,
    forwardingPrefix: (kind: string, name: string) => `Forwarding ${kind}/${name}...`,
    forwardingOnLoopback: (port: number) => `Forwarding on 127.0.0.1:${port}`,
    socketFailed: 'Port forwarding socket failed.',
  },
  topbar: {
    openMenu: 'Open menu',
    userMenu: 'User menu',
    settings: 'Settings',
    preferences: 'Preferences',
    loadingSettings: 'Loading settings...',
    closeSettings: 'Close settings',
    theme: 'Theme',
    logLevel: 'Log level',
    effectivePrefix: 'Effective:',
    envPrefix: 'ENV:',
    uiOverrideActive: 'UI override active',
    desktopOnly: 'Log level is editable only in desktop mode.',
    failedToUpdateLogLevel: 'Failed to update log level.',
    saving: 'Saving...',
    rolePrefix: 'Role:',
    permissionsSuffix: 'permissions',
  },
  resource: {
    selectContextToBegin: 'Select a context to begin. Use the Azure panel to pull AKS credentials.',
    searchPods: 'Search Pods...',
    filterByName: 'Filter by name...',
    refreshingResourcesAfterAuth: 'Refreshing resources after authentication',
    refreshing: 'Refreshing...',
    liveSync: 'Live sync',
    connecting: 'Connecting',
    showEventsFromRange: 'Show events from this time range',
    allTime: 'All time',
    last5Minutes: 'Last 5 minutes',
    last15Minutes: 'Last 15 minutes',
    last1Hour: 'Last 1 hour',
    last6Hours: 'Last 6 hours',
    last24Hours: 'Last 24 hours',
    exportFilteredResources: 'Export the filtered resources',
    retry: 'Retry',
    addNewResource: 'Add a new resource (deploy YAML)',
    addNewResourceLabel: 'Add a new resource',
    loading: 'Loading…',
    noResourcesFound: 'No resources found.',
    selectAll: 'Select all',
    clickToSort: 'Click to sort',
    nothingToExport: 'Nothing to export — the filtered list is empty.',
  },
  applications: {
    title: 'Applications',
    selectedCountSuffix: 'selected',
    refresh: 'Refresh',
    copyInstance: 'Copy Instance',
    instance: 'Instance',
    application: 'Application',
    namespace: 'Namespace',
    managedBy: 'Managed By',
    version: 'Version',
    age: 'Age',
    status: 'Status',
    metrics: 'Metrics',
    metricsDescription: 'Displaying metrics from Kubernetes Metrics Server',
    cpuUsage: 'CPU Usage',
    properties: 'Properties',
    pods: 'Pods',
    workloadResources: 'Workload Resources',
    loadingPods: 'Loading pods…',
    noPodsFound: 'No pods found',
  },
  observability: {
    selectContext: 'Please select a Kubernetes context from the sidebar to view event correlations.',
    timeRange: 'Time Range:',
    workloadChanges: 'Workload Changes:',
    warningEvents: 'Warning Events:',
    correlated: 'Correlated:',
    noEventsInRange: 'No events recorded in this time range.',
    time: 'Time:',
    namespace: 'Namespace:',
    category: 'Category:',
    changeType: 'Change Type:',
    severity: 'Severity:',
    summary: 'Summary:',
    correlation: 'Correlation:',
    reason: 'Reason:',
    involvedObject: 'Involved Object:',
    before: 'Before:',
    after: 'After:',
  },
  observabilityPanel: {
    selectContext: 'Please select a Kubernetes context from the sidebar to use observability features.',
    loading: 'Loading...',
    unavailableTitle: 'Observability Unavailable',
    unavailableDescription: 'Something went wrong loading the observability store. Try reloading, or check the backend logs for details.',
    title: 'Observability & Time-Travel Debugging',
    subtitle: 'Record and replay cluster state changes over time.',
    recording: 'Recording',
    stopRecording: 'Stop Recording',
    starting: 'Starting...',
    retry: 'Retry',
    startRecording: 'Start Recording',
    timelineTab: '◷ Timeline',
    logsTab: '📋 Multi-Pod Logs',
    correlationTab: '🔗 Event Correlation',
    recordingNotActivePrefix: 'Recording not active:',
    startRecordingHint: 'Click "Start Recording" above to begin capturing cluster state changes. Without an active recording, the',
    timelineScrubber: 'timeline scrubber',
    correlationDashboard: 'correlation dashboard',
    willShowNoData: 'will show no data.',
  },
  timeline: {
    selectContext: 'Please select a Kubernetes context from the sidebar to view the timeline.',
    clusterStatePrefix: 'Cluster State at',
    noWorkloadState: 'No workload state recorded at this time.',
    kind: 'Kind',
    namespace: 'Namespace',
    name: 'Name',
    changeType: 'Change Type',
    summary: 'Summary',
    uid: 'UID',
    severity: 'Severity',
    reason: 'Reason',
    before: 'Before:',
    after: 'After:',
    clusterScoped: '(cluster-scoped)',
  },
  multiPodLogs: {
    pods: 'Pods:',
    podNamesPlaceholder: 'Enter pod names (e.g., my-pod-1, my-pod-2) separated by commas',
    filterPlaceholder: 'Filter logs...',
    enterPodsHint: 'Enter pod names above to start viewing merged logs from multiple replicas.',
    waitingForLogs: 'Waiting for logs...',
  },
  topology: {
    selectContext: 'Select a context to view its topology.',
    title: 'Topology',
    loading: 'Loading…',
    selectNamespace: 'Select a namespace…',
    selectNamespaceToView: 'Select a namespace to view its object graph.',
    selectApplicationsToView: 'Select one or more applications to view their topology.',
    noObjectsFound: 'No objects found for the selected application(s).',
    couldNotLoadPrefix: "Couldn't load:",
    inThisNamespace: 'in this namespace — the graph below reflects everything else.',
  },
  resourceDetail: {
    logs: 'Logs',
    shell: 'Shell',
    restartDeployment: 'Restart Deployment',
    deploymentActions: 'Deployment Actions',
    editYaml: 'Edit YAML',
    deletePrefix: 'Delete',
    name: 'Name',
    kind: 'Kind',
    warningPrefix: 'WARNING: You are deleting pod',
    destructiveActionNotice: 'This is an immediate destructive action and may interrupt traffic.',
    continuePrompt: 'Do you want to continue?',
    yaml: 'YAML',
    overview: 'Overview',
    details: 'Details',
    pod: 'Pod',
    deployment: 'Deployment',
    clusterScoped: '(cluster-scoped)',
    readOnlyNotice: 'Read-only — your role cannot edit this resource.',
    decoding: 'Decoding…',
    decodedValues: 'Decoded values (server-side, requires ALLOW_SECRET_REVEAL=true)',
    properties: 'Properties',
    metrics: 'Metrics',
    metricsDescription: 'Displaying metrics from Kubernetes Metrics Server',
    noVolumesDefined: 'No volumes defined',
    containers: 'Containers',
    vulnerabilities: 'Vulnerabilities',
    events: 'Events',
    loadingEvents: 'Loading events…',
    noEventsFound: 'No events found',
    images: 'Images',
    labels: 'Labels',
    annotations: 'Annotations',
    status: 'Status',
    image: 'Image',
    ports: 'Ports',
    environment: 'Environment',
    mounts: 'Mounts',
    requests: 'Requests',
    limits: 'Limits',
    created: 'Created',
  },
  sidebar: {
    k8sCluster: 'K8S Cluster',
    starredContexts: 'STARRED CONTEXTS',
    noStarredContexts: 'No starred contexts yet.',
    azureConnections: 'Azure connections',
    awsConnections: 'AWS connections',
    azureAccounts: ' Azure / AKS',
    awsAccounts: 'AWS / EKS',
    loadingAzureAccounts: 'Loading Azure accounts...',
    checkAzureAccount: 'Click Azure / AKS to check cloud account.',
    noResourceGroups: 'No resource groups found.',
    noClustersFound: 'No clusters found.',
    noContextImported: 'No context imported yet.',
    loadingAwsClusters: 'Loading AWS clusters...',
    checkAwsAccount: 'Click AWS / EKS to check cloud account.',
    noEksClustersFound: 'No EKS clusters found.',
  },
  columns: {
    chooseVisible: 'Choose visible columns',
    visibleColumns: 'Visible columns',
    resetColumns: 'Reset Columns',
  },
  aws: {
    connectionsTitle: 'AWS / EKS Connections',
    accountTitle: 'AWS / EKS Account',
    checking: 'Checking...',
    configureConnection: 'Configure AWS connection',
    configureDescription: 'Choose SSO, access keys, or an IAM role profile for this session.',
    saveConnection: 'Save AWS connection',
    signIn: 'Sign in to AWS (device code)',
    signInProgress: 'AWS sign-in in progress...',
    waitingForDeviceCode: 'Waiting for AWS device code...',
    waitingForSignIn: 'Waiting for sign-in...',
    signOut: 'Sign out',
    signedOut: 'Signed out from AWS CLI SSO session.',
    signedIn: 'Signed in to AWS.',
    importCredsPrefix: 'Imported credentials for',
    loadingClusters: 'Loading clusters...',
    noClusters: 'No EKS clusters.',
    refresh: 'Refresh',
  },
  azure: {
    connectionsTitle: 'Azure / AKS Connections',
    accountTitle: 'Account',
    checking: 'Checking…',
    signIn: 'Sign in to Azure (device code)',
    signInProgress: 'Azure sign-in in progress…',
    waitingForDeviceCode: 'Waiting for Azure device code…',
    waitingForSignIn: 'Waiting for sign-in…',
    signOut: 'Sign out',
    signedOut: 'Signed out from Azure CLI session.',
    signedIn: 'Signed in to Azure.',
    importCredsPrefix: 'Imported credentials for',
    loadingClusters: 'Loading clusters…',
    noClusters: 'No AKS clusters.',
    refresh: 'Refresh',
  },
  deployment: {
    readOnlyNotice: 'Your role is read-only — deployment actions are disabled.',
    restart: 'Restart',
    rolloutRestart: 'Rollout restart',
    scale: 'Scale',
    apply: 'Apply',
    currentDesiredPrefix: 'current desired:',
    rolloutHistory: 'Rollout history',
    loadingHistory: 'Loading history…',
    revision: 'Revision',
    images: 'Images',
    created: 'Created',
    current: 'current',
    rollback: 'Rollback',
  },
  logs: {
    container: 'Container',
    follow: 'Follow',
    openInTerminal: 'Open in terminal tab',
    streaming: 'streaming',
    disconnected: 'disconnected',
  },
  exec: {
    container: 'Container',
    shell: 'Shell',
    terminal: 'Terminal',
    openInTerminal: 'Open in terminal',
    connected: 'connected',
    disconnected: 'disconnected',
  },
  terminalDock: {
    resizePanel: 'Resize terminal panel',
    dragToResize: 'Drag to resize terminal',
    openNewTerminal: 'Open new terminal',
    restoreTerminals: 'Restore terminals',
    minimizeTerminals: 'Minimize all terminals',
    shell: 'Shell',
    logs: 'Logs',
    ready: 'Ready',
    connected: 'connected',
    disconnected: 'disconnected',
    searchTerminal: 'Search terminal',
    searchTerminalContents: 'Search terminal contents',
  },
} as const;

export type UiText = typeof uiText;